rvm:
  - 1.8.7
  - ree
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-2.2.1

script: "bundle exec rake --trace"

notifications:
  recipients:
    - nahi@ruby-lang.org
