rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-2

script: "bundle exec rake --trace"

notifications:
  recipients:
    - nahi@ruby-lang.org

matrix:
  allow_failures:
    - rvm: rbx-2
